// Generated by gowls
// https://github.com/friedelschoen/wayland/cmd/gowls
// XML file : proto/cursor-shape-v1.xml
//
// cursor_shape_v1 Protocol Copyright:
//
// Copyright 2018 The Chromium Authors
// Copyright 2023 Simon Ser
//
// Permission is hereby granted, free of charge, to any person obtaining a
// copy of this software and associated documentation files (the "Software"),
// to deal in the Software without restriction, including without limitation
// the rights to use, copy, modify, merge, publish, distribute, sublicense,
// and/or sell copies of the Software, and to permit persons to whom the
// Software is furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice (including the next
// paragraph) shall be included in all copies or substantial portions of the
// Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
// THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
// FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//

// Package proto contains wayland-protocol cursor_shape_v1
package proto

import wayland "github.com/friedelschoen/wayland"
import "runtime"
import "fmt"

// CursorShapeManager : cursor shape manager
//
// This global offers an alternative, optional way to set cursor images. This
// new way uses enumerated cursors instead of a wl_surface like
// wl_pointer.set_cursor does.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
type CursorShapeManager struct {
	wayland.BaseProxy
	children []wayland.Proxy
}

// NewCursorShapeManager : cursor shape manager
//
// This global offers an alternative, optional way to set cursor images. This
// new way uses enumerated cursors instead of a wl_surface like
// wl_pointer.set_cursor does.
//
// Warning! The protocol described in this file is currently in the testing
// phase. Backward compatible changes may be added together with the
// corresponding interface version bump. Backward incompatible changes can
// only be done by creating a new major version of the extension.
func NewCursorShapeManager() *CursorShapeManager {
	return &CursorShapeManager{}
}
func (i *CursorShapeManager) Name() string {
	return "wp_cursor_shape_manager_v1"
}

// Destroy : destroy the manager
//
// Destroy the cursor shape manager.
func (i *CursorShapeManager) Destroy() {
	destroyCursorShapeManager(i.BaseProxy)
}
func destroyCursorShapeManager(p wayland.BaseProxy) {
	i := &p
	if i == nil || !i.Valid() {
		return
	}
	w := wayland.NewMessageWriter(i, 0)
	if err := w.Finish(); err != nil {
		panic(err)
	}
}

// GetPointer : manage the cursor shape of a pointer device
//
// Obtain a wp_cursor_shape_device_v1 for a wl_pointer object.
//
// When the pointer capability is removed from the wl_seat, the
// wp_cursor_shape_device_v1 object becomes inert.
func (i *CursorShapeManager) GetPointer(pointer *Pointer) *CursorShapeDevice {
	if i == nil || !i.Valid() {
		return nil
	}
	cursorShapeDevice := NewCursorShapeDevice()
	i.Conn().Register(cursorShapeDevice)
	i.children = append(i.children, cursorShapeDevice)
	w := wayland.NewMessageWriter(i, 1)
	w.WriteObject(cursorShapeDevice)
	w.WriteObject(pointer)
	if err := w.Finish(); err != nil {
		panic(err)
	}
	return cursorShapeDevice
}

// GetTabletToolV2 : manage the cursor shape of a tablet tool device
//
// Obtain a wp_cursor_shape_device_v1 for a zwp_tablet_tool_v2 object.
//
// When the zwp_tablet_tool_v2 is removed, the wp_cursor_shape_device_v1
// object becomes inert.
func (i *CursorShapeManager) GetTabletToolV2(tabletTool wayland.Proxy) *CursorShapeDevice {
	if i == nil || !i.Valid() {
		return nil
	}
	cursorShapeDevice := NewCursorShapeDevice()
	i.Conn().Register(cursorShapeDevice)
	i.children = append(i.children, cursorShapeDevice)
	w := wayland.NewMessageWriter(i, 2)
	w.WriteObject(cursorShapeDevice)
	w.WriteObject(tabletTool)
	if err := w.Finish(); err != nil {
		panic(err)
	}
	return cursorShapeDevice
}
func (i *CursorShapeManager) Register(conn *wayland.Conn, id uint32) {
	i.BaseProxy.Register(conn, id)
	if conn != nil && id != 0 {
		runtime.AddCleanup(i, destroyCursorShapeManager, i.BaseProxy)
	}
}
func (i *CursorShapeManager) Dispatch(msg *wayland.Message, drain chan<- wayland.Event) {
}

// CursorShapeDevice : cursor shape for a device
//
// This interface allows clients to set the cursor shape.
type CursorShapeDevice struct {
	wayland.BaseProxy
	children []wayland.Proxy
}

// NewCursorShapeDevice : cursor shape for a device
//
// This interface allows clients to set the cursor shape.
func NewCursorShapeDevice() *CursorShapeDevice {
	return &CursorShapeDevice{}
}
func (i *CursorShapeDevice) Name() string {
	return "wp_cursor_shape_device_v1"
}

// Destroy : destroy the cursor shape device
//
// Destroy the cursor shape device.
//
// The device cursor shape remains unchanged.
func (i *CursorShapeDevice) Destroy() {
	destroyCursorShapeDevice(i.BaseProxy)
}
func destroyCursorShapeDevice(p wayland.BaseProxy) {
	i := &p
	if i == nil || !i.Valid() {
		return
	}
	w := wayland.NewMessageWriter(i, 0)
	if err := w.Finish(); err != nil {
		panic(err)
	}
}

// SetShape : set device cursor to the shape
//
// Sets the device cursor to the specified shape. The compositor will
// change the cursor image based on the specified shape.
//
// The cursor actually changes only if the input device focus is one of
// the requesting client's surfaces. If any, the previous cursor image
// (surface or shape) is replaced.
//
// The "shape" argument must be a valid enum entry, otherwise the
// invalid_shape protocol error is raised.
//
// This is similar to the wl_pointer.set_cursor and
// zwp_tablet_tool_v2.set_cursor requests, but this request accepts a
// shape instead of contents in the form of a surface. Clients can mix
// set_cursor and set_shape requests.
//
// The serial parameter must match the latest wl_pointer.enter or
// zwp_tablet_tool_v2.proximity_in serial number sent to the client.
// Otherwise the request will be ignored.
//
// serial : serial number of the enter event
func (i *CursorShapeDevice) SetShape(serial uint32, shape CursorShapeDeviceShape) {
	if i == nil || !i.Valid() {
		return
	}
	w := wayland.NewMessageWriter(i, 1)
	w.WriteUint(uint32(serial))
	w.WriteUint(uint32(shape))
	if err := w.Finish(); err != nil {
		panic(err)
	}
}
func (i *CursorShapeDevice) Register(conn *wayland.Conn, id uint32) {
	i.BaseProxy.Register(conn, id)
	if conn != nil && id != 0 {
		runtime.AddCleanup(i, destroyCursorShapeDevice, i.BaseProxy)
	}
}

type CursorShapeDeviceShape uint32

// CursorShapeDeviceShape : cursor shapes
//
// This enum describes cursor shapes.
//
// The names are taken from the CSS W3C specification:
// https://w3c.github.io/csswg-drafts/css-ui/#cursor
// with a few additions.
//
// Note that there are some groups of cursor shapes that are related:
// The first group is drag-and-drop cursors which are used to indicate
// the selected action during dnd operations. The second group is resize
// cursors which are used to indicate resizing and moving possibilities
// on window borders. It is recommended that the shapes in these groups
// should use visually compatible images and metaphors.
const (
	// CursorShapeDeviceShapeDefault : default cursor
	CursorShapeDeviceShapeDefault CursorShapeDeviceShape = 1
	// CursorShapeDeviceShapeContextMenu : a context menu is available for the object under the cursor
	CursorShapeDeviceShapeContextMenu CursorShapeDeviceShape = 2
	// CursorShapeDeviceShapeHelp : help is available for the object under the cursor
	CursorShapeDeviceShapeHelp CursorShapeDeviceShape = 3
	// CursorShapeDeviceShapePointer : pointer that indicates a link or another interactive element
	CursorShapeDeviceShapePointer CursorShapeDeviceShape = 4
	// CursorShapeDeviceShapeProgress : progress indicator
	CursorShapeDeviceShapeProgress CursorShapeDeviceShape = 5
	// CursorShapeDeviceShapeWait : program is busy, user should wait
	CursorShapeDeviceShapeWait CursorShapeDeviceShape = 6
	// CursorShapeDeviceShapeCell : a cell or set of cells may be selected
	CursorShapeDeviceShapeCell CursorShapeDeviceShape = 7
	// CursorShapeDeviceShapeCrosshair : simple crosshair
	CursorShapeDeviceShapeCrosshair CursorShapeDeviceShape = 8
	// CursorShapeDeviceShapeText : text may be selected
	CursorShapeDeviceShapeText CursorShapeDeviceShape = 9
	// CursorShapeDeviceShapeVerticalText : vertical text may be selected
	CursorShapeDeviceShapeVerticalText CursorShapeDeviceShape = 10
	// CursorShapeDeviceShapeAlias : drag-and-drop: alias of/shortcut to something is to be created
	CursorShapeDeviceShapeAlias CursorShapeDeviceShape = 11
	// CursorShapeDeviceShapeCopy : drag-and-drop: something is to be copied
	CursorShapeDeviceShapeCopy CursorShapeDeviceShape = 12
	// CursorShapeDeviceShapeMove : drag-and-drop: something is to be moved
	CursorShapeDeviceShapeMove CursorShapeDeviceShape = 13
	// CursorShapeDeviceShapeNoDrop : drag-and-drop: the dragged item cannot be dropped at the current cursor location
	CursorShapeDeviceShapeNoDrop CursorShapeDeviceShape = 14
	// CursorShapeDeviceShapeNotAllowed : drag-and-drop: the requested action will not be carried out
	CursorShapeDeviceShapeNotAllowed CursorShapeDeviceShape = 15
	// CursorShapeDeviceShapeGrab : drag-and-drop: something can be grabbed
	CursorShapeDeviceShapeGrab CursorShapeDeviceShape = 16
	// CursorShapeDeviceShapeGrabbing : drag-and-drop: something is being grabbed
	CursorShapeDeviceShapeGrabbing CursorShapeDeviceShape = 17
	// CursorShapeDeviceShapeEResize : resizing: the east border is to be moved
	CursorShapeDeviceShapeEResize CursorShapeDeviceShape = 18
	// CursorShapeDeviceShapeNResize : resizing: the north border is to be moved
	CursorShapeDeviceShapeNResize CursorShapeDeviceShape = 19
	// CursorShapeDeviceShapeNeResize : resizing: the north-east corner is to be moved
	CursorShapeDeviceShapeNeResize CursorShapeDeviceShape = 20
	// CursorShapeDeviceShapeNwResize : resizing: the north-west corner is to be moved
	CursorShapeDeviceShapeNwResize CursorShapeDeviceShape = 21
	// CursorShapeDeviceShapeSResize : resizing: the south border is to be moved
	CursorShapeDeviceShapeSResize CursorShapeDeviceShape = 22
	// CursorShapeDeviceShapeSeResize : resizing: the south-east corner is to be moved
	CursorShapeDeviceShapeSeResize CursorShapeDeviceShape = 23
	// CursorShapeDeviceShapeSwResize : resizing: the south-west corner is to be moved
	CursorShapeDeviceShapeSwResize CursorShapeDeviceShape = 24
	// CursorShapeDeviceShapeWResize : resizing: the west border is to be moved
	CursorShapeDeviceShapeWResize CursorShapeDeviceShape = 25
	// CursorShapeDeviceShapeEwResize : resizing: the east and west borders are to be moved
	CursorShapeDeviceShapeEwResize CursorShapeDeviceShape = 26
	// CursorShapeDeviceShapeNsResize : resizing: the north and south borders are to be moved
	CursorShapeDeviceShapeNsResize CursorShapeDeviceShape = 27
	// CursorShapeDeviceShapeNeswResize : resizing: the north-east and south-west corners are to be moved
	CursorShapeDeviceShapeNeswResize CursorShapeDeviceShape = 28
	// CursorShapeDeviceShapeNwseResize : resizing: the north-west and south-east corners are to be moved
	CursorShapeDeviceShapeNwseResize CursorShapeDeviceShape = 29
	// CursorShapeDeviceShapeColResize : resizing: that the item/column can be resized horizontally
	CursorShapeDeviceShapeColResize CursorShapeDeviceShape = 30
	// CursorShapeDeviceShapeRowResize : resizing: that the item/row can be resized vertically
	CursorShapeDeviceShapeRowResize CursorShapeDeviceShape = 31
	// CursorShapeDeviceShapeAllScroll : something can be scrolled in any direction
	CursorShapeDeviceShapeAllScroll CursorShapeDeviceShape = 32
	// CursorShapeDeviceShapeZoomIn : something can be zoomed in
	CursorShapeDeviceShapeZoomIn CursorShapeDeviceShape = 33
	// CursorShapeDeviceShapeZoomOut : something can be zoomed out
	CursorShapeDeviceShapeZoomOut CursorShapeDeviceShape = 34
	// CursorShapeDeviceShapeDndAsk : drag-and-drop: the user will select which action will be carried out (non-css value)
	CursorShapeDeviceShapeDndAsk CursorShapeDeviceShape = 35
	// CursorShapeDeviceShapeAllResize : resizing: something can be moved or resized in any direction (non-css value)
	CursorShapeDeviceShapeAllResize CursorShapeDeviceShape = 36
)

func (e CursorShapeDeviceShape) Name() string {
	switch e {
	case CursorShapeDeviceShapeDefault:
		return "default"
	case CursorShapeDeviceShapeContextMenu:
		return "context_menu"
	case CursorShapeDeviceShapeHelp:
		return "help"
	case CursorShapeDeviceShapePointer:
		return "pointer"
	case CursorShapeDeviceShapeProgress:
		return "progress"
	case CursorShapeDeviceShapeWait:
		return "wait"
	case CursorShapeDeviceShapeCell:
		return "cell"
	case CursorShapeDeviceShapeCrosshair:
		return "crosshair"
	case CursorShapeDeviceShapeText:
		return "text"
	case CursorShapeDeviceShapeVerticalText:
		return "vertical_text"
	case CursorShapeDeviceShapeAlias:
		return "alias"
	case CursorShapeDeviceShapeCopy:
		return "copy"
	case CursorShapeDeviceShapeMove:
		return "move"
	case CursorShapeDeviceShapeNoDrop:
		return "no_drop"
	case CursorShapeDeviceShapeNotAllowed:
		return "not_allowed"
	case CursorShapeDeviceShapeGrab:
		return "grab"
	case CursorShapeDeviceShapeGrabbing:
		return "grabbing"
	case CursorShapeDeviceShapeEResize:
		return "e_resize"
	case CursorShapeDeviceShapeNResize:
		return "n_resize"
	case CursorShapeDeviceShapeNeResize:
		return "ne_resize"
	case CursorShapeDeviceShapeNwResize:
		return "nw_resize"
	case CursorShapeDeviceShapeSResize:
		return "s_resize"
	case CursorShapeDeviceShapeSeResize:
		return "se_resize"
	case CursorShapeDeviceShapeSwResize:
		return "sw_resize"
	case CursorShapeDeviceShapeWResize:
		return "w_resize"
	case CursorShapeDeviceShapeEwResize:
		return "ew_resize"
	case CursorShapeDeviceShapeNsResize:
		return "ns_resize"
	case CursorShapeDeviceShapeNeswResize:
		return "nesw_resize"
	case CursorShapeDeviceShapeNwseResize:
		return "nwse_resize"
	case CursorShapeDeviceShapeColResize:
		return "col_resize"
	case CursorShapeDeviceShapeRowResize:
		return "row_resize"
	case CursorShapeDeviceShapeAllScroll:
		return "all_scroll"
	case CursorShapeDeviceShapeZoomIn:
		return "zoom_in"
	case CursorShapeDeviceShapeZoomOut:
		return "zoom_out"
	case CursorShapeDeviceShapeDndAsk:
		return "dnd_ask"
	case CursorShapeDeviceShapeAllResize:
		return "all_resize"
	default:
		return ""
	}
}
func (e CursorShapeDeviceShape) String() string {
	return fmt.Sprintf("%s=%d", e.Name(), e)
}

type CursorShapeDeviceError uint32

// CursorShapeDeviceError :
const (
	// CursorShapeDeviceErrorInvalidShape : the specified shape value is invalid
	CursorShapeDeviceErrorInvalidShape CursorShapeDeviceError = 1
)

func (e CursorShapeDeviceError) Name() string {
	switch e {
	case CursorShapeDeviceErrorInvalidShape:
		return "invalid_shape"
	default:
		return ""
	}
}
func (e CursorShapeDeviceError) String() string {
	return fmt.Sprintf("%s=%d", e.Name(), e)
}
func (i *CursorShapeDevice) Dispatch(msg *wayland.Message, drain chan<- wayland.Event) {
}
func GetCursorShapeInterface(name string) wayland.Proxy {
	switch name {
	case "wp_cursor_shape_manager_v1":
		return NewCursorShapeManager()
	case "wp_cursor_shape_device_v1":
		return NewCursorShapeDevice()
	default:
		return nil
	}
}
